folderIndex = {
  'logs':{
    'staff_logs':{
      'log00':`It's been quite a while since I've left the complex. Cave had ordered me to work overtime on the ASMOPT. He seems to be becoming increasingly paranoid that NASA is incredibly close to winning the space race and stealing his spotlight. I had to stay in the loading bay for 13 hours today, just observing that each and every piece is properly assembled as shown on the blueprints I designed. I'm not sure how he thinks harnessing a black hole in an underground facility is a good idea, but I can't find work anywhere else, and this pays well.`,
      'log01':`Things are looking slightly better. Aperture has just opened a new test shaft that showcases the use of the ASOMPT on a tiny, and more controlled scale. I've personally designed and checked every single tiny ASOMPT that Aperture has produced, and I can confidently say that they're as safe as they can be. The only downside to this being that this test shaft was extremely costly. I'm not sure where we're going to find the funding that will support the safety measures that we need for the large ASOMPT to be safe. `,
      'log02':`The test shaft didn't last long. Lawsuits are being filed and government funding has ceased. As a result, Kilo Franklin has been permanently closed. I think the death count was nearing twenty before someone finally put a stop to it. Hopefully this will sway some executive into shutting down the project. I certainly don't know how much more I can handle.`,
      'log03':`I've been promoted to head of the project, and yet I still have no say in whatever decisions are made. The other day when we announced that astronauts can sign up to test the ASOMPT? I didn't have anything to do with it. I just hope people realize the dangers that this presents before they sign up.`,
      'log04':`Today they announced the "lucky" astronauts that get to be the first to test the ASOMPT, and bring Aperture to the front of the science frontier. They consider them "test subjects", I consider them victims. I've genuinely thought about stomping into Caves office and telling him to shut the whole thing down. This is becoming madness, it's lunacy, and I've had enough. People's lives are in my hands, and I'm not sure how I feel about it.`,
      'log05':`I've just been informed that we're not taking extensive safety measures to keep the astronauts safe. We're not even treating them like people anymore. They're human, and we're shoving them through a black hole! And this is all due to Johnsons stupid obsession of being the best at everything. You would think that the CEO of a science company would have some common sense.`,
      'log06':`Today was the final construction day on the machine. It's finally complete and I don't know if I should be relieved or extremely concerned. On one hand, my job is done. I have enough money to retire, and I don't have any more responsibilities. On the other hand, Aperture refused to spend any extra money on the safety protocols, so I'm not confident in the odds of those poor astronauts coming back alive. I'm dreading the day on which we send them through, it's giving me a lack of sleep. This project ate up years of my life and is something that no one has ever achieved before, but I regret accepting the invitation to be an engineer in the first place.`,
      'log07':`They have decided to send them through a few weeks early, which makes this whole scenario even worse. I've been checking out the stability of the black hole, and it appears to have a trend. Just about every week and a half, it's gravitational pull increases by over 130%, sometimes more. That means it has enough force to rip an aluminum can to shreds, I hate to think of what it could do to a human. Then the pull turns back to normal in the next day or so. Unfortunately, the new date just so happens to be on one of these days. I've tried to warn someone, but no one is acknowledging my existence ever since I left. They've also figured out a way to keep all of the pressure created by the black hole in the black hole. Which has its positives and negatives. For one, it makes sure that nothing gets sucked into the hole. But for two, if it becomes unstable and collapses, it will explode with the force of a nuclear bomb, and then it'll begin to suck things in with 300 times the gravitational pull on Earth. I plan to be there when it happens.`,
      'log08':`It's one week until we turn the ASOMPT on, and the astronauts still are being left in the dark about the dangers they're in for. The other day I was told that I can no longer legally interfere with the machine or the computational devices that keep it operational. Meaning that I can no longer check the stability of the black hole they're harnessing. I doubt any calculations have changed, but on the off chance it has changed for the worse, no one else knows how to read those dials and graphs. If something changes for the worse it would most likely mean that the second we turn it on, and remove the idling state, the black hole will instantly collapse. I still feel as if their lives are in my hands, but I can't do anything to keep them safe.`,
      'log09':`Tomorrow's the big day, they're finally turning on what I've worked on for the past 5 years. It's going to be both amazing and terrifying to watch, and although I designed and observed the creation of the ASOMPT, I still have no idea what to expect. I doubt it will be anything good. I managed to get a peak at the pressure dials today, and their values are still increasing. I would've tried a manual restart on the whole thing, except I was caught tampering with the internal circuitry by a passing security guard. I plan on typing out what happens tomorrow after the event. Anyways, my hands are shaking and I should probably get some sleep.`
    },
    'nov_2_65.txt':`Greeting, Astronaut! If you're reading this that means you got handed a keycard at the beginning of your check in. That keycard can be used to access test shaft Kilo Franklin, where you will be testing the [redacted] for the remainder of your stay here at Aperture Science. Please take the next left and descend down the stairs, once you arrive in front of the airlock an Aperture Science Employee will provide instructions and remind you of the safety procedures.`,
    'jan_5_64.txt':`Aperture Science Innovators is proud to announce the opening of test shaft Kilo Franklin which centers itself around the Aperture Science [redacted]. You and your family can enjoy mind boggling puzzles for the low price of $199! So, what are you waiting for! Come on down to Kilo Franklin, and enjoy your stay at Aperture Science!`,
    'dec_9_64.txt':`Due to recent events related to the Aperture Science [redacted] test shaft Kilo Franklin has been closed to the public and is not expected to return. Now, this begs the question: How do I access test shaft Kilo Franklin? The simple answer is to become an Astronaut. Starting on the new year Aperture Science will begin taking applications to test the [redacted]. Training and safety measures will be provided.`,
    'jan_21_65.txt':`Aperture Science is happy to announce that all spots on the application form have been taken! We currently have 12 enlisted astronauts, two of which are ready to test the [redacted]. Aperture Science would also like to address the concerns the public have over this experiment. Don't worry, the [redacted] has been tested and it works fine and is completely safe 50% of the time. That's a 25% increase since it was last opened to the public!`,
    'aug_19_69.txt':`Aperture Science regrets to report that the Aperture Science [redacted] experiment did not go as planned. This will result in the condemnation of test shaft Kilo Franklin and the 1960s branch of the facility. However, don't be alarmed, Aperture is doing just fine financially and will continue it's experiments in the coming years.`
  },
  'credits.txt':`APERTURE 77 ARG

Website created by Baguettery
Content written by Terrorcows`
}
